- install.sh
If multiple configs were previously specified, when installing/reinstalling/upgrading, the installer only looks for a single:string value but we get a multi-line and the installer fails.
> Multiple configs detection during install/reinstall

- host/service/merlin/service.go
localtime is ignored if TZ variable is set.
> Unset TZ variable to fix time zone in syslog

- Dockerfile
Updating Go version to sync with https://github.com/nextdns/nextdns/commit/372b627241e75fd0cc02621d09c8fc6f34d09ff2.
> Update Go version to match release.yml

- discovery/dhcp.go
On OPNSense, the DHCP leases are stored in `/var/dhcpd/var/db/dhcpd.leases`. This patch adds these to the `leaseFiles` array.
I don't know how you came up with the current list but if it's something evolving, here's a patch to make it also work under OPNSense (20.1+).
> discovery/dhcp.go: Add isc-dhcpd leases on OPNSense

- install.sh
The script had mixed commands for upgrading an uninstalling NextDNS on deb-based distributions. That effectively meant that trying to upgrade NextDNS would uninstall it, and trying to uninstall it would simply upgrade it. This PR fixes that issue by correcting the commands for each of those options.
A few trailing whitespace characters were also removed, but that can be staged separately, for cleanliness sake ;-)
> Fixed upgrade / uninstall options on deb-based distributions

- .github/workflows/release.yml
This PR fixes the issue with checks failing in OpenWRT.
There were 2 possibilities in to solve these issues:
Option 1: Hardcode everything to `Olivier Poitrey <rs@nextdns.io>`
Option 2: Define the author based on author of the commit.
I opted for option 2 because this is more in line with the reality of the commit history.
On that note, I don't know if OpenWRT checks if the author is the same as `PKG_MAINTAINER` which is configured in the package. If they do, we might need to revisit this, because I have noticed the following commit in the commit history:
```
commit 9cdc17eb5451a979a993c7a89085a4e1f7817795
Author: Olivier Poitrey <rs@xxxxxxx.net>
Date:   Mon May 4 16:24:42 2020 -0700
Update issue templates
```
As you can see, the email(domain redacted for your privacy even though its a …
> ci: fix commit author in OpenWRT flow

- install.sh
Ref: https://developer.github.com/v3/#user-agent-required
This makes the script work in environments where user agent is disabled via `.curlrc` (or similar means.)
> install.sh: always set a user-agent for api.github.com

- install.sh
> unifi-os: limit the install/upgrade to nextdns package only

- host/service/synology/service.go
This PR fixes the Synology init script to get service status. May need more checking to ensure it works on all models, the current implementation doesn't work on some models including the DS918+ (#413 ).
> Fix  problem with testing service status on the Synology init

- install.sh
Add `vyos` to the installer script case statements.
VyOS `/etc/os-release` `ID` was changed from `debian` to `vyos` on [Feb 23](https://github.com/vyos/vyos-build/commit/e218a757616d27a5c31a3c39a175c5e73a376f23#diff-875a9be0f0342ad3b8430148a75ebdd02afce1fadd535ad8547c244de3d9fd9dR109).
The proposed changes fix the issues detailed in #440 
Tested on `1.4-rolling-202103251004`.
> Fix support for VyOS

- install.sh
OpenSUSE Leap is basically the opensource stable version of SuSE. In
the future, it should even be on par with SLE. Handle it like any
other SuSE distribution (with zypper).
> Support OpenSUSE Leap in installer

- host/service/upstart/service.go
initctl binary is also present for SysV system. Debian not running
systemd would be misdetected as Upstart. The usual way to detect if
Upstart is installed and running is to query `initctl version`.
This fix has been tested on Debian 8 without systemd, Ubuntu 14 with
Upstart not running and Ubuntu 14 with Upstart running.
> Fix detection of Upstart init

- install.sh
The `command` builtin is optional in Busybox shell. Use `which` as it
is likely to be present as, historically, it is the most often used
method (but in POSIX). See
https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then/85250#85250.
> Fix installation when Busybox shell does not support "command"

- host/service/synology/service.go
Add a check to the Synology init script to identify whether we are running under Busybox, if so then use a different method to get the running pid.
> Update the Synology init script to cater for underlying shell being Busybox

- host/log_linux.go
As of firmware version 386.1, Merlin added the Busybox logread applet, so it is in the path, but non-functional because syslogd is still writing to a file and not shared memory.
This PR checks for the /jffs/syslog.log file before checking for the logread command.
Fixes #469
> Fix nextdns log command on ASUSWRT-Merlin

- config/config.go
- host/service/config.go
- proxy/proxy.go
- proxy/tcp.go
- proxy/udp.go
With a default limit of 256 inflight requests, a latency of 3ms to
NextDNS, asking `dnsperf` to run at 100 QPS, there is no change in
latency (which is expected).
The limit can be adjusted using `-max-inflight-requests`. Ideally,
this could be tuned depending on the memory available on the system,
but it seems complex to do that portably in Go. I think 256 is a fine
limit for most systems. We could have a different default limit for
smaller archs (like mips) if we wanted to do some kind of "detection".
> proxy: limit the number of concurrent inflight requests

- .github/workflows/release.yml
- .github/workflows/snapshot-push.yml
- .github/workflows/snapshot.yml
Due to security concerns, actions running on a pull_request workflow do not have access to secrets. The workflow need to be cut in two: the untrusted part will test and build and upload the result as an artifact. The trusted part will take the artifact and upload it.
Downloading the artifact is a bit complex until actions/download-artifact is able to do that for us (see https://github.com/actions/download-artifact/issues/60). The code snippet is stolen from https://securitylab.github.com/research/github-actions-preventing-pwn-requests/.
It is a bit a pain to test as it needs to be merged in master before being able to test. I hope to get this right at the first try. Otherwise, I'll try to test in my own fork.
> Make snapshot action work when we are not rs

- .github/workflows/snapshot-cleanup.yml
This enables access to credentials. This is safe as long as we don't
checkout/execute any untrusted code.
> When cleaning snapshots, use pull_request_target

- .github/workflows/snapshot-test.yml
The tests are currently quite simple:
- install NextDNS
- run some `nextdns` command
- activate NextDNS
- resolve some random names
The tests rely on cloud images with cloud-init enabled. They also
rely on ability to use 9P to pass the test script (this could be done
differently) and to retrieve the result (a bit harder to do
differently, but we could pass the result through a serial console).
It should be easy to add other cloud-init-enabled Linux but maybe it
could be extended to BSDs (see https://bsd-cloud-image.org/).
One drawback is that if there is a failure outside of the test script,
the VMs will just linger idle for 15 minutes. The VMs are running at
slow speed because nested virtualization is not available inside
GitHub environment. Otherwise, the tests would run in less than a …
> Add integration tests using Fedora/Ubuntu/Debian cloud images

- config/config.go
- host/service/config.go
- proxy/proxy.go
- proxy/tcp.go
- proxy/udp.go
- run.go
With a default limit of 256 inflight requests, a latency of 3ms to
NextDNS, asking `dnsperf` to run at 100 QPS, there is no change in
latency (which is expected).
The limit can be adjusted using `-max-inflight-requests`. Ideally,
this could be tuned depending on the memory available on the system,
but it seems complex to do that portably in Go. I think 256 is a fine
limit for most systems. We could have a different default limit for
smaller archs (like mips) if we wanted to do some kind of "detection".
This is similar to #521, except with a missing chunk added to not make it break. **Do not merge**, I am pushing it to test some CI stuff.
> proxy: limit the number of concurrent inflight requests (#521)

- resolver/endpoint/manager.go
On first use, an endpoint need to be initialized by testing it. When
several requests are processed while no endpoint has finished
initializing, additional endpoints are instantiated and tested,
leading to parallel execution of all the tests until a stable endpoint
is found.
Record the initialization endpoint as the active endpoint once it has
been built to avoid this. The endpoint still needs to be tested but
this is done under a lock to avoid parallelism. Moreover, once the
final endpoint is selected, the active endpoint is replaced by it.
The fix seems simple but it is a bit difficult to navigate in the
code. I was going to isolate the whole endpoint selection/testing into
a dedicated goroutine that would provide the active endpoint by
message passing, but this seems quite a risky …
> resolver: avoid parallel initialization of endpoints

- .github/workflows/snapshot-test.yml
When turned into a string, objects are converted to `[object Object]`.
Use `console.log()` directly on them.
> github: fix debug display for snapshot test workflow

- .github/workflows/snapshot.yml
`GITHUB_SHA` is the reference to the merge commit of the pull request.
To get the HEAD sha, we need to use
`github.event.pull_request.head.sha`. As we have a checkout, just use
rev-parse which works if we have a PR or not.
> github: fix SHA reference when building snapshots

- .github/workflows/snapshot.yml
On a pull request, the checkout tree is also a merged tree. So, use
`github.event.pull_request.head.sha` for pull request and keep
GTIHUB_SHA for master.
> github: fix (again) SHA reference for snapshot

- config/config.go
The help text instructs to use `disable` to disable mDNS client discovery. This will cause NextDNS to report an error in the log that `disable` is an unknown interface. The correct value to use is `disabled`.
> Fix help text for mDNS option

- .github/workflows/release.yml
There was a change in how Debian packages are built. The
"Architecture" field of the generated Debian packages are now a bit
different and we need to adapt.
Instead of trying to map Go architectures to Debian architectures then
to other architectures, I am mapping Go architectures to
Debian/Alpine/RPM architectures.
On Debian:
- armv5 → nothing
- armv6 → armel
- armv7 → armhf (see https://www.debian.org/releases/stable/armhf/release-notes/ch-whats-new.en.html#idm120)
On Raspbian, this was not the same as their port was using hard-float
ABI on ARMv6, but the armel version should work fine. And Raspbian is
a bit a thing of the past I think.
On Alpine:
- armv6 → armhf
- armv7 → armv7
On RPM distributions, ARMv7 distribution is armhfp. I am also fixing
the official name used for x86_64. …
> github: fix architecture mapping

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .github/workflows/staticcheck.yml
This reverts commit fe5e5b4ef8af18d75263cc68d215e617cbba316f. We
switch back to 1.16.5 just for testing. It was known to work with
1.35.0. If it works, we need to try 1.16.10 then.
> Revert "Switch to go 1.17"

- .github/workflows/release.yml
Debian says armhf is armv7 min, but Raspbian allows armv6. So, fix the
mapping. Fix #623.
> github: fix mapping for Debian-like distributions

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
It was the one used to build v1.37.3 which mapped armhf to ARMv6.
v1.37.4 is using GoReleaser v1.0.0 which maps armhf to ARMv7. This is
a workaround until we understand what happens.
> github: use GoReleaser v0.182.1

- .github/workflows/release.yml
- .github/workflows/snapshot.yml
In Homebrew, `bottle :unneeded` has been deprecated.
[#11239 - formula_auditor: don't allow bottle :unneeded in core.](https://github.com/Homebrew/brew/pull/11239)
The aforementioned issue has been addressed since GoReleaser 0.183.0, and can be resolved by upgrading.
> Proposal: Bump GoReleaser from v0.182.1

- .github/workflows/release.yml
For Debian repositories, the key needs to *not* be armored as this is
only supported since APT 1.4 (so Debian Stretch and Ubuntu Trusty
needs a non-armored key).
As reported on #558, on RPM distributions, the key is expected to be
armored and some implementations only work with an armored key.
So, we generate both key formats, we keep `nextdns.gpg` for Debian and
we use `nextdns-armored.gpg` for RPM.
Fix #558.
> release: use an armored key for RPM repositories

- config/config.go
Quick spelling fix! I doubt specified servers should be separated by prolonged periods of unconsciousness.
Keep up the great work!
> Fix spelling in forwarder flag description

- config.go
- ctl/internal/winio/backup.go
- ctl/internal/winio/backup_test.go
- ctl/internal/winio/ea_test.go
- ctl/internal/winio/fileinfo_test.go
- host/dns_bsd.go
- host/dns_linux.go
- host/service/bsd/service.go
- host/service/merlin/service.go
- host/service/openrc/service.go
- host/service/procd/service.go
- host/service/runit/service.go
- host/service/systemd/service.go
- host/service/ubios/service.go
- router/merlin/setup.go
- router/synology/setup.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
> refactor: move from io/ioutil to io and os packages

- .github/workflows/release.yml
CentOS 8 is out of support since end of 2021 and the repositories have
been moved to vault.centos.org. The Docker images have not been
updated. We patch the repository definitions to use vault.centos.org.
An alternative would be to use Fedora as a base instead, but it seems
safer to use CentOS 8 since it works and we know the repositories
created by the version of createrepo is CentOS work.
> release: use centos:8 image but modify repo list to use vault.centos.org

- .github/workflows/release.yml
This is a clone of CentOS 8. It is maintained and a dropin
replacement, so we don't need to patch centos:8 image to use
vault.centos.org.
> release: use almalinux:8 image instead of centos:8 for createrepo

- install.sh
Per #564, allows installation on systemd-based gentoo systems. This is untested on openrc-based gentoo installations.
For systemd-based installations you may need to stop and disable the systemd-resolved service prior to installation.
> Update install.sh to support installation on gentoo

- .github/workflows/release.yml
- .goreleaser/deb/postinst
- install.sh
Maybe it would help with failed upgrades for Unifi as users are reporting the file to disappear when placed in /usr/share/keyrings. We apply the change for all Debian-derivative to avoid confusion. /etc/apt/keyrings may even be a better location because /usr/share/keyrings should only contain files installed from the package manager.
May fix #755
> Move GPG key file for Debian in /etc/apt/keyrings

- discovery/dhcp.go
Fedora and it's decendants (CentOS and then RHEL) override the default location for the dnsmasq.leases file from `/var/lib/misc/dnsmasq.leases` to `/var/lib/dnsmasq/dnsmasq.leases`.
This adds it to the list.
See the upstream patch on this change:
https://src.fedoraproject.org/rpms/dnsmasq/blob/rawhide/f/dnsmasq-2.81-configuration.patch#_79
> discovery: add fedora/centos/rhel dnsmasq lease location

- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- .github/workflows/staticcheck.yml
Thanks for merging my last pull request. I realized there was much more to update when I checked it out right now. This updates almost all actions that have actions and go to 1.19.5 where it isnt
> workflow: update go to 1.19.5, codeql to v2, goreleaser to v4

- discovery/dhcp.go
- discovery/dhcp_test.go
Hi @rs, here is a quick fix for a regression I found.
`*` hostnames in the dnsmasq lease file were previously ignored during discovery (see https://github.com/nextdns/nextdns/commit/a533720b781de6e00efc33eda461fc73d636195a) but this change was accidentally lost during refactoring ([see here](https://github.com/nextdns/nextdns/commit/29b36779b4ca0a02cbe15627a252374f8d3d1c34#diff-a03cef345cd9a9be021d714665b8c3224e84ccb481c7ecab2d8d2aa052450bd9L95-L97)).
I also remove a redundant duplicate call to `absDomainName`.
Please let me know what you think. Thanks!
> Skip * hostnames in dnsmasq lease file

- discovery/merlin_linux.go
On new firmwares, after reboot, the '<' char in the beginning of the string is removed (not a bug?). This fix attemps to add it if non present.
This fixes #839
> Fix missing '<' on custom_clientlist

- host/log_bsd.go
- host/log_darwin.go
- host/log_linux.go
- host/log_other.go
- service.go
I submitted this [feature request](https://github.com/nextdns/nextdns/issues/357) a couple of years back and finally had time to implement it. It enables journald log following on Linux systems only.
An optional follow flag `-f/--follow` has been added to the `log` command. If not specified, then the default log behavior will persist.
I have tested this on my machine using:
- `go build`
- `./nextdns log -f`
- Logs are streamed to stdout.
Happy to close if this isn't something that's deemed needed. I can also unit test all of this if we decide to go ahead with the new functionality.
> host: implement log following for systemd-journald

- .github/workflows/release.yml
By default, a shallow clone is done and git log does not have the full log. Request a full clone to avoid that.
> Fix changelog on releases

- install.sh
On some platforms, like UDM, the APT configuration may be broken beyond despair (see #830 or #909). We don't really care about dependencies as we don't have any. Just ignore the error. APT will still update NextDNS repository.
> install: ignore "apt-get update" errors

- .github/workflows/snapshot.yml
- .github/workflows/staticcheck.yml
By default, a shallow clone is done and git log does not have the full log. Request a full clone to avoid that.
Related pull Request : #908
> Fix changelog for workflows

- .github/workflows/release.yml
When syncing new metadata files, set a max age of 5 minutes and ask for revalidation past that. This minimizes the time these files are out-of-date.
This relies on the fact that aws s3 sync only updates metadata for changed files.
> github: avoid caching metadata files for too long

- .goreleaser/apk/post-upgrade
- .goreleaser/deb/postinst
- .goreleaser/rpm/post
This should stop the overwriting of a user set bogus-priv=false during update process.
#952
> Remove unneeded "-bogus-priv" setting on update

- .github/workflows/release.yml
Signature of APK repository happens later. We don't sign packages. I think this should fix #990.
An alternative would be to pin Alpine to 3.19.0 instead of 3.19.
> fix: reenable APK generation and don't check for signature too early

- install.sh
Add opensuse-slowroll distribution to install script.
Fixes Issue #987
> opensuse-slowroll
