nextdns/nextdns

- README.md
Minor corrections, typo fixes.
> Update spelling in README

- install.sh
elementary is the same thing as ubuntu basically. Fixes: #71
> support for elementary OS

- router/merlin/setup.go
Take into account the resolv-file entry present on John’s fork instead of servers-file.
> dnsmasq.postconf update for ASUSWRT-Merlin-LTS

- install.sh
Creates solus support using "bin method".
Solves #69.
Should probably delve into https://getsol.us/articles/packaging/ for cleaner inclusion.
> Added Solus support 

- install.sh
This PR adds openSUSE Tumbleweed support.
> Added support for openSUSE (Tumbleweed & Leap)

- install.sh
> Add detection for EdgeOS on UniFi Security Gateway

- proxy/udp.go
- proxy/udp_unix.go
- proxy/udp_windows.go
> fix for windows not implemented errors

- install.sh
I started used nextdns on my mac and now I started using in my in my new laptop linux, but sadly missing Pop!_OS distribution in this great service.
My humble contribution.
Good luck!
> ADD: Pop!_OS distribution added

- README.md
"WIP" since full integration (OPNsense UI) is not yet provided, and neither is the port.
> Update README: "WIP" for OPNsense

- .github/workflows/release.yml
⚠️ WIP ⚠️  
An attempt to automate release to OpenWRT. Would love to hear your thoughts.
The idea behind this is to automate creating of PR towards OpenWRT with the `Makefile` updated with the version number + updated hash.
Resolves https://github.com/nextdns/nextdns/issues/182
> ci: automate release to OpenWRT

- install.sh
KDE neon is based off of Ubuntu
> Add support for KDE neon

- install.sh
Default Debian installs don't have curl, just wget. This is handled to
install the repository, but not to fetch the latest available version.
Try to find the best command available for this purpose. Busybox' wget
also has a `-U`, so there should be no problem on most embedded
systems.
> Fix installation script for Debian without curl

- host/service/runit/service.go
- host/service_linux.go
- install.sh
This PR adds support for Voidlinux and runit init.
Closes: #258
> Add support for Voidlinux (runit init)

- install.sh
We need to download the GPG key and annotate the source to use it.
Fix #478
> install.sh: fix installation on ubios platform

- proxy/proxy.go
On slow systems, it is possible that nextdns is unable to shutdown due
to the `Close()` method for TCP or UDP not being called and not
interrupting `Accept()`. The `closeAll` array should be protected by a
lock.
Example on 1.32.3:
```
SIGQUIT: quit
PC=0x900a0 m=0 sigcode=0goroutine 35 [syscall]:
runtime.notetsleepg(0x65d640, 0xffffffff, 0xffffffff, 0x433600)
/opt/hostedtoolcache/go/1.16.4/x64/src/runtime/lock_futex.go:235 +0x48 fp=0x8a2fcc sp=0x8a2fb4 pc=0x1c6bc
os/signal.signal_recv(0x48b730)
/opt/hostedtoolcache/go/1.16.4/x64/src/runtime/sigqueue.go:168 +0x118 fp=0x8a2fe0 sp=0x8a2fcc pc=0x8c614
os/signal.loop()
/opt/hostedtoolcache/go/1.16.4/x64/src/os/signal/signal_unix.go:23 +0x34 fp=0x8a2fec sp=0x8a2fe0 pc=0x195f10
runtime.goexit() …
```
> Fix rare occurrence of nextdns not shutting down

- router/ubios/setup.go
In commit 8ee250abaa16, to divert DNS traffic to NextDNS, the traffic
was selected using RFC1918 address as a destination. We can do that
more cleanly by specifically asking Netfilter to match any local
address.
Note this matches comment of 8ee250abaa16 "Make UDM only capturing DNS
traffic directed at the router", but this does not have the same
effect. Notably, it works if the router is not using RFC 1918 but it
would also work if traffic is targeting the public IP address of the
external interface, which may not be what we expect. However, the
FORWARD rules should still apply.
@rs I need to discuss this change with you, this is part of a more global effort.
> For UDM Pro, divert traffic to NextDNS using addrtype instead of RFC1918

- .github/workflows/snapshot-push.yml
- Move dist.zip, PR and NAME out of the way
- Fix JS error on comment
- Append index.html to URL
> Fix snapshot push workflow

- .github/workflows/snapshot-push.yml
- .github/workflows/snapshot-test.yml
- .github/workflows/snapshot.yml
This displays integration tests progress and results inside the "Check" section of the PR.
> Integrate snapshot test inside "check" section of a pull request

- .github/workflows/snapshot-test.yml
For some reason, the status of the tests are not added to the PR. It
was working on my repository. Let's add some debug to understand why
this happens. Notably, owner/repo may not be set correctly.
This needs to be merged as is to be able to test: we cannot test this
workflow in a PR.
> Add some debug for snapshot tests

- resolver/endpoint/doh.go
This should help with #546 and determine if we get the certificate we
expect and if it is signed by the right authority.
> resolver: put some more details on "Unknwon authority error"

- Dockerfile
- go.mod
Updates go from 1.19.1 to 1.19.5 in the dockerfile
> dockerfile: go 1.19.1 to 1.19.5

- Dockerfile
- go.mod
- go.sum
Updates golang sys and net to the latest and updates dockerfile to the newly released go 1.20
> Update golang sys and net to latest, update docker to go 1.20

- config/forwarder.go
- config/profile.go
- ctl/internal/winio/sd.go
- host/service/launchd/launchctl.go
- install.sh
- internal/dnsmessage/message.go
- resolver/endpoint/manager.go
- run.go
- service.go
Corrected some typos in go files.
> Text corrections in go files

- host/service/ubios/service.go
- install.sh
- router/ubios/setup.go
> Add support for UXG series of Unifi product

- discovery/mdns.go
- discovery/mdns_test.go
- discovery/util.go
> Add a 1000 limit on the number of hostnames discovered via mdns

- .goreleaser.yml
> ci: fix goreleaser config
